version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: mongo-service
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONGO_URI=mongodb://mongo:27017/taskmanager
    depends_on:
      - mongo

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - USER_SERVICE_URL=http://user-service:3002
      - JWT_SECRET=adm_secret_key
    depends_on:
      - user-service

  task-service:
    build: ./task-service
    container_name: task-service
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - MONGO_URI=mongodb://mongo:27017/taskmanager
    depends_on:
      - mongo

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - TASK_SERVICE_URL=http://task-service:3003
    depends_on:
      - task-service

  orchestrator-service:
    build: ./orchestrator-service
    container_name: orchestrator-service
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - AUTH_SERVICE_URL=http://auth-service:3001
      - USER_SERVICE_URL=http://user-service:3002
      - TASK_SERVICE_URL=http://task-service:3003
      - NOTIFICATION_SERVICE_URL=http://notification-service:3004
      - JWT_SECRET=adm_secret_key
    depends_on:
      - auth-service
      - user-service
      - task-service
      - notification-service

volumes:
  mongo_data: