apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator-service
  template:
    metadata:
      labels:
        app: orchestrator-service
    spec:
      containers:
        - name: orchestrator-service
          image: adm-orchestrator-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: AUTH_SERVICE_URL
              value: http://auth-service:3001
            - name: USER_SERVICE_URL
              value: http://user-service:3002
            - name: TASK_SERVICE_URL
              value: http://task-service:3003
            - name: NOTIFICATION_SERVICE_URL
              value: http://notification-service:3004
---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator-service
spec:
  selector:
    app: orchestrator-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
  type: NodePort